### ISSUE TITLE
A key can only consist of ASCII letter, digit or '_' (underscore) characters.

### ISSUE THREAD

**Issue by neit-group-admin** [oracle/oracle-functions-samples#35]
Hello everyone,

Ad func.py
How come you have got for example this:
schema = cfg["db-schema"]?
Given the fact that hyphens are not allowed.

Fn: Error updating function configuration: Service error:InvalidParameter. Invalid config. http status code: 400.

Thanks and Regards,
Vaclav

**Comment by sachin-pikle** [comment]
Hi Vaclav,

Sorry about the delayed reply.

Yes, it looks like a bug (to be confirmed). Earlier we used to allow hyphens "-" in function config variable names. Can you replace the hyphens in function config variable names with underscores please "_" ?

Regards
Sachin Pikle.

**Comment by sachin-pikle** [comment]
Hi Vaclav,

This issue is fixed. Can you try again and confirm?

Regards
Sachin Pikle.

**Comment by neit-group-admin** [comment]
Hi Sachin,

It seems to be ok from the Cloud Shell perspective. However, there is still the same warning in the GUI form.

Thanks and Regards,
Vaclav

**Comment by sachin-pikle** [comment]
Hi Vaclav,

The GUI fix is awaiting deployment. Will let you know once that's in production.

Regards
Sachin Pikle.

**Comment by sachin-pikle** [comment]
Hi Vaclav,

The console/GUI fix has been deployed in production. I am closing the issue. If you still see this issue, please add a comment and reopen this ticket. Thank you!

Regards
Sachin Pikle.

**Comment by neit-group-admin** [comment]
Hi Sachin,

Thumbs up! 

Thanks a lot.

Regards,
Vaclav
